version: '3'

services:
  node-red:
    image: nodered/node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    networks:
      - custom_bridge
    volumes:
      - node_red_data:/data

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - custom_bridge

networks:
  custom_bridge:
    driver: bridge

volumes:
  node_red_data:
    driver: local
